{% set name = "nbformat" %}
{% set version = "5.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbformat-{{ version }}.tar.gz
  sha256: 9ebe30e6c3b3e5b47d39ff0a3897a1acf523d2bfafcb4e2d04cdb70f8a66c507

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
    - wheel
  run:
    - python
    - jsonschema >=2.6
    - jupyter_core
    - python-fastjsonschema
    - traitlets >=5.1

test:
  source_files:
    - tests
  imports:
    - nbformat
  requires:
    - pip
    - pytest
    - pytest-cov
    - testpath
  commands:
    - pip check
    - jupyter trust --version
    - jupyter-trust --help
    - pytest -vv --cov nbformat --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 79

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  summary: The Jupyter Notebook format
  license_file: COPYING.md
  doc_url: https://nbformat.readthedocs.io
  dev_url: https://github.com/jupyter/nbformat 

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer