{% set version = "5.1.3" %}

package:
  name: nbformat
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  sha256: b516788ad70771c6250977c1374fcca6edebe6126fd2adb5a69aa5c2356fd1c8

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jsonschema >=2.4,!=2.5.0
    - jupyter_core
    - python-fastjsonschema
    - traitlets >=4.1

test:
  source_files:
    - tests
  commands:
    - pip check
    - jupyter trust --version
    - jupyter-trust --help
    - pytest -vv --cov nbformat --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 79
  requires:
    - pip
    - pytest
    - pytest-cov
    - testpath
  imports:
    - nbformat

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  summary: The Jupyter Notebook format
  license_file: COPYING.md
  doc_url: https://nbformat.readthedocs.io
  dev_url: https://github.com/jupyter/nbformat 

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer