{% set name = "nbformat" %}
{% set version = "5.7.0" %}
{% set sha256 = "1d4760c15c1a04269ef5caf375be8b98dd2f696e5eb9e603ec2bf091f9b0d3f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbformat-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-nodejs-version
  run:
    - python
    - importlib_metadata >=3.6
    - jsonschema >=2.6
    - jupyter_core
    - python-fastjsonschema
    - traitlets >=5.1

test:
  source_files:
    - tests
  imports:
    - nbformat
  requires:
    - pip
    - pytest
    - pytest-cov
    - testpath
  commands:
    - pip check
    - jupyter trust --version
    - jupyter-trust --help
    # pep440 is required for passing tests/test_api.py
    - pip install pep440
    - pytest -vv --cov nbformat --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 79

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: The Jupyter Notebook format
  description: | 
    This package contains the base implementation of the Jupyter Notebook format,
    and Python APIs for working with notebooks.
  doc_url: https://nbformat.readthedocs.io
  dev_url: https://github.com/jupyter/nbformat 

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer