{% set version = "5.1.2" %}

package:
  name: nbformat
  version: {{ version }}

source:
  # TODO: Using github source for build 1 because the PyPI source was missing
  # schema.json files. Should be fixed in v5.1.2 (revert to PyPI source then).
  # url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  # sha256: ce34144c29b27db6b22d2f5205babf8b4dead1f0be1766caf49ab4b994c50570
  url: https://github.com/jupyter/nbformat/archive/{{ version }}.tar.gz
  sha256: ce34144c29b27db6b22d2f5205babf8b4dead1f0be1766caf49ab4b994c50570

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - ipython_genutils
    - traitlets >=4.1
    - jsonschema >=2.4,!=2.5.0
    - jupyter_core

test:
  commands:
    - pip check
    - jupyter-trust -h
  requires:
    - pip
  imports:
    - nbformat

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  summary: The Jupyter Notebook format
  license_file: COPYING.md
  summary: The reference implementation of the Jupyter Notebook format
  description: |
    nbformat contains the reference implementation of the Jupyter Notebook
    format, and Python APIs for working with notebooks.
  doc_url: http://nbformat.readthedocs.org
  dev_url: https://github.com/jupyter/nbformat

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer
