{% set version = "5.1.1" %}

package:
  name: nbformat
  version: {{ version }}

source:
  # TODO: Using github source for build 1 because the PyPI source was missing
  # schema.json files. Should be fixed in v5.1.2 (revert to PyPI source then).
  # url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  # sha256: ce5d4d7989d85d4c59631d84fed475f899ac637bd33f100737d796af20b47ddd
  url: https://github.com/jupyter/nbformat/archive/{{ version }}.tar.gz
  sha256: f8da48c751f7547ba5b69d824b8cfc5b63e5f1245040050faf56b04974f8ddbd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - ipython_genutils
    - traitlets >=4.1
    - jsonschema >=2.4,!=2.5.0
    - jupyter_core

test:
  commands:
    - pip check
    - jupyter-trust -h
  requires:
    - pip
  imports:
    - nbformat

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  summary: The Jupyter Notebook format
  license_file: COPYING.md
  summary: The reference implementation of the Jupyter Notebook format
  description: |
    nbformat contains the reference implementation of the Jupyter Notebook
    format, and Python APIs for working with notebooks.
  doc_url: http://nbformat.readthedocs.org
  dev_url: https://github.com/jupyter/nbformat

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - mpacer
