travis:
  secure:
    BINSTAR_TOKEN: LzibXovpQBy030XnOb1hVX6jPqK0OWPCrqPmNcuG3xOxmMxurNYDkrWqP+pREX3M41Z3bfkgjtTlurXlWSqKzpzSOPn6KcPo2hSt2PHrP2OGSe1KbfWx7mJUG1uDgEem/0dugUH9G06p6En9dwmWqaUxumuy01+fw9Nh941djaJauGuROtzexk/6zSSZDN94OvfHHiji+DSSnqXyMm24+yixSuXLjP/+hk1/hLOtGppDykstNYQQzqYQ1yu1agvE+q3fykdfKJ3bV7uIMxPAjfSuVv9hc9XH4LznUu+a7ZoOraI+55knPGubP0vGnZTmec8cwF8ymzkk6xcUAVV6Kok40YjezKi8zWInxCaRAiGtFug67Q0hsd/9f4HfTWGAsqOrlE6ICz1dTnCoY2HEDa4HrRzW2y+74e1JcZZeoAFwjMalI8OmPHnAd3pfrg2wNk1Ay/GGf+WNAAfzCJZjnGEGxn5klgCHj2ghVDRFr14QoeCKMFHGyQhDd/TTHbuYxPzrCEPAU27/8d7GtV9zjFYh1zZYeY6XxLjK+67anpQeU1EKy4oEUBKQoX2jYVwg34Ll6ncmi5WqmhPV8nN4cpaJIq70KJxHMbaC5Aic9Dmh6ZIOT+DNBXjhP64bOrQ0OOndkmeBtrvniIWoq9ZOlP0CXmmn0fzfIWZyIJi9k1I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
